# Generated by Django 2.0.1 on 2018-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
